version: "3"

services:
  api:
    container_name: dev_django_tech
    restart: always
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./mysite/.env
    depends_on:
      - postgres

  postgres:
    container_name: db_postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./mysite/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
