version: "3"

services:
  api:
    container_name: prod_django_tech
    restart: always
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - 8010:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./mysite/.env
    depends_on:
      - postgres

  postgres:
    container_name: db_postgres
    image: postgres
    restart: always
    env_file:
      - ./mysite/.env
    volumes:
      - postgres-db-prod:/var/lib/postgresql/data

volumes:
  postgres-db-prod:
