# Generated by Django 4.0.4 on 2022-06-04 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
